FROM python:3.8-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /home/usr/pythonsample/

COPY requirements.txt ./requirements.txt

COPY shell/entrypoint_second_app.sh ./entrypoint.sh

ENTRYPOINT [ "sh","./entrypoint.sh" ]
