FROM python:3.8-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /home/usr/pythonsample/

COPY requirements.txt ./requirements.txt

COPY shell/entrypoint_without_volumes.sh ./entrypoint.sh

COPY ./scripts/kub_sample_without_volumes.py ./kub_sample.py

ENTRYPOINT [ "sh","./entrypoint.sh" ]
