apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment1
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-kubefirst
        image: sri-dock-vol
        imagePullPolicy: Never
        env:
        - name: first_arg
          valueFrom:
            configMapKeyRef:
              name: python-program
              key: name
        - name: second_arg
          valueFrom:
            configMapKeyRef:
              name: python-program
              key: value
        args: ["$(first_arg)","$(second_arg)"]
        